INSERT INTO topic (id, name, created) VALUES (UUID(), 'C', NOW());
INSERT INTO topic (id, name, created) VALUES (UUID(), 'C++', NOW());
INSERT INTO topic (id, name, created) VALUES (UUID(), 'C#', NOW());
INSERT INTO topic (id, name, created) VALUES (UUID(), 'Java', NOW());
INSERT INTO topic (id, name, created) VALUES (UUID(), 'Python', NOW());
INSERT INTO message (id, text, author, created, topic_id) VALUES (UUID(), 'Компилируемый язык программирования', 'Деннис Ричи', NOW(), (SELECT id FROM topic WHERE name = 'C'));
INSERT INTO message (id, text, author, created, topic_id) VALUES (UUID(), 'Компилируемый язык программирования C++', 'Бьёрн Страуструп ', NOW(), (SELECT id FROM topic WHERE name = 'C++'));
INSERT INTO message (id, text, author, created, topic_id) VALUES (UUID(), 'Объектно-ориентированный язык программирования C#', 'Андерс Хейлсберг', NOW(), (SELECT id FROM topic WHERE name = 'C#'));
INSERT INTO message (id, text, author, created, topic_id) VALUES (UUID(), 'Объектно-ориентированный язык программирования Java', 'Джеймс Гослинг,', NOW(), (SELECT id FROM topic WHERE name = 'Java'));
INSERT INTO message (id, text, author, created, topic_id) VALUES (UUID(), 'Высокоуровневый язык программирования Python', 'Гвидо ван Россум', NOW(), (SELECT id FROM topic WHERE name = 'Python'));